version: "3.9"
services:
  db:
    image: postgres
    container_name: goBlogAws_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - goBlog_data:/var/lib/postgresql/data
    expose:
      - 5432
  app:
    container_name: goBlog
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - db
    expose:
      - 8000

volumes:
  goBlog_data: